//! Render [`ParsedSave`] back to iptables-save / iptables-restore text.
//!
//! Output is stable (canonical key order) so that snapshots diff cleanly.
//! The renderer pre-allocates output buffers and writes tokens directly,
//! avoiding the per-rule `Vec<String>` + `join` overhead that scales poorly
//! at thousands of rules.

use crate::model::{ChainSpec, Counters, ParsedSave, ParsedTable, Rule, RuleSpec, TableKind};
use std::fmt::Write;

/// Render a full save dump that can be fed to `iptables-restore`.
pub fn render_save(parsed: &ParsedSave) -> String {
    let total_rules: usize = parsed.tables.values().map(|t| t.rules.len()).sum();
    let total_chains: usize = parsed.tables.values().map(|t| t.chains.len()).sum();
    let estimated = total_rules.saturating_mul(96) + total_chains.saturating_mul(40) + 256;
    let mut out = String::with_capacity(estimated);
    let _ = writeln!(out, "# Generated by iptables-dashboard");
    // canonical table order
    for kind in [
        TableKind::Raw,
        TableKind::Mangle,
        TableKind::Nat,
        TableKind::Filter,
        TableKind::Security,
    ] {
        if let Some(table) = parsed.tables.get(&kind) {
            render_table(&mut out, table);
        }
    }
    out
}

fn render_table(out: &mut String, table: &ParsedTable) {
    let _ = writeln!(out, "*{}", table.kind);
    for c in &table.chains {
        render_chain(out, c);
    }
    for r in &table.rules {
        render_rule(out, r);
    }
    let _ = writeln!(out, "COMMIT");
}

fn render_chain(out: &mut String, c: &ChainSpec) {
    let policy = c.policy.map(|p| p.as_str()).unwrap_or("-");
    match c.counters {
        Some(Counters { packets, bytes }) => {
            let _ = writeln!(out, ":{} {} [{}:{}]", c.name, policy, packets, bytes);
        }
        None => {
            let _ = writeln!(out, ":{} {} [0:0]", c.name, policy);
        }
    }
}

fn render_rule(out: &mut String, r: &Rule) {
    if let Some(Counters { packets, bytes }) = r.counters {
        let _ = write!(out, "[{}:{}] ", packets, bytes);
    }
    let _ = write!(out, "-A {}", r.chain);
    let saved_len = out.len();
    out.push(' ');
    write_spec(out, &r.spec);
    if out.len() == saved_len + 1 {
        // No tokens emitted — strip the trailing space.
        out.pop();
    }
    out.push('\n');
}

/// Render a single rule body (everything after `-A CHAIN`) to a fresh String.
/// Kept as a public API for places that need the rendered form (e.g. parser
/// canonicalising `Rule::raw`).
pub fn render_spec(s: &RuleSpec) -> String {
    let mut out = String::with_capacity(96);
    write_spec(&mut out, s);
    out
}

/// Append the rule body tokens to `out`, separated by single spaces. No
/// leading or trailing whitespace is inserted; the caller is responsible
/// for surrounding context.
pub fn write_spec(out: &mut String, s: &RuleSpec) {
    let mut w = TokenWriter::new(out);

    if let Some(p) = &s.protocol {
        w.push_with_neg("-p", p);
    }
    if let Some(v) = &s.source {
        w.push_with_neg("-s", v);
    }
    if let Some(v) = &s.destination {
        w.push_with_neg("-d", v);
    }
    if let Some(v) = &s.in_interface {
        w.push_with_neg("-i", v);
    }
    if let Some(v) = &s.out_interface {
        w.push_with_neg("-o", v);
    }
    if let Some(true) = s.fragment {
        w.push("-f");
    }
    if let Some(v) = &s.sport {
        w.push("--sport");
        w.push(v);
    }
    if let Some(v) = &s.dport {
        w.push("--dport");
        w.push(v);
    }

    for m in &s.matches {
        // Skip the `comment` match if `comment` is already exposed on spec —
        // we re-emit it below in canonical position.
        if m.name == "comment" && s.comment.is_some() && m.args.iter().any(|a| a == "--comment") {
            continue;
        }
        w.push("-m");
        w.push(&m.name);
        for a in &m.args {
            w.push(a);
        }
    }

    if let Some(comment) = &s.comment {
        w.push("-m");
        w.push("comment");
        w.push("--comment");
        w.push_quoted(comment);
    }

    if let Some(j) = &s.jump {
        w.push("-j");
        w.push(j);
        for a in &s.target_args {
            if needs_quotes(a) {
                w.push_quoted(a);
            } else {
                w.push(a);
            }
        }
    } else if let Some(g) = &s.goto {
        w.push("-g");
        w.push(g);
    }

    for x in &s.extra {
        w.push(x);
    }
}

struct TokenWriter<'a> {
    buf: &'a mut String,
    first: bool,
}

impl<'a> TokenWriter<'a> {
    fn new(buf: &'a mut String) -> Self {
        Self { buf, first: true }
    }
    fn push(&mut self, s: &str) {
        if !self.first {
            self.buf.push(' ');
        }
        self.buf.push_str(s);
        self.first = false;
    }
    fn push_with_neg(&mut self, flag: &str, value: &str) {
        if let Some(rest) = value.strip_prefix('!') {
            self.push("!");
            self.push(flag);
            self.push(rest);
        } else {
            self.push(flag);
            self.push(value);
        }
    }
    fn push_quoted(&mut self, s: &str) {
        if !self.first {
            self.buf.push(' ');
        }
        self.buf.push('"');
        for c in s.chars() {
            match c {
                '\\' => self.buf.push_str("\\\\"),
                '"' => self.buf.push_str("\\\""),
                other => self.buf.push(other),
            }
        }
        self.buf.push('"');
        self.first = false;
    }
}

fn needs_quotes(s: &str) -> bool {
    s.contains(char::is_whitespace) || s.contains('"')
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::Family;
    use crate::parser::parse_save;

    fn assert_round_trip(input: &str, family: Family) {
        let parsed = parse_save(input, family).expect("parse");
        let rendered = render_save(&parsed);
        let reparsed = parse_save(&rendered, family).expect("re-parse");
        assert_eq!(parsed, reparsed, "round trip diverged\n--- rendered ---\n{rendered}");
    }

    #[test]
    fn round_trip_simple_filter() {
        let input = r#"*filter
:INPUT ACCEPT [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
COMMIT
"#;
        assert_round_trip(input, Family::V4);
    }

    #[test]
    fn round_trip_with_log_prefix() {
        let input = r#"*filter
:INPUT DROP [0:0]
-A INPUT -j LOG --log-prefix "iptables drop: " --log-level 4
COMMIT
"#;
        assert_round_trip(input, Family::V4);
    }

    #[test]
    fn round_trip_v6_icmpv6() {
        let input = r#"*filter
:INPUT ACCEPT [0:0]
-A INPUT -p ipv6-icmp -m icmp6 --icmpv6-type 134 -j ACCEPT
COMMIT
"#;
        assert_round_trip(input, Family::V6);
    }

    #[test]
    fn render_spec_empty_is_empty() {
        let s = RuleSpec::default();
        assert_eq!(render_spec(&s), "");
    }

    #[test]
    fn render_spec_quoting_escapes_backslash_and_quote() {
        let mut s = RuleSpec::default();
        s.jump = Some("LOG".into());
        s.target_args = vec!["--log-prefix".into(), "weird \"a\\b\" prefix".into()];
        let out = render_spec(&s);
        assert!(out.contains("\"weird \\\"a\\\\b\\\" prefix\""), "got: {out}");
    }
}
